### ISSUE TITLE
Disable always-on-top

### ISSUE THREAD

**Issue by BlueMax** [x42/meters.lv2#26]
All meter windows are always-on-top (Arch/XFCE/Carla) and i can't let them run in background without closing all windows manually. Other plugins behave properly (Calf, wolf spectrum..). 
Can you make that optional?

**Comment by x42** [comment]
Why would you want a meter-window in the background, if you don't look at it?

**Comment by BlueMax** [comment]
I switch back and forth through apps. I use Carla as my main audio app to hear/analyze music in the background at home. Your plugins are outstanding to make audio "visible". Your missing a spectrogram like [wolf spectrum](https://github.com/pdesaulniers/wolf-spectrum) though. :-)

**Comment by x42** [comment]
I never found a spectrum-analyzer by itself useful in musical context: [x42-eq](https://github.com/x42/fil4.lv2) features a spectrum analyzer with perceptual frequency warping. As a technical tool, there's https://github.com/x42/spectra.lv2  -- that does resolve individual frequencies. e.g. https://github.com/x42/spectra.lv2/issues/2#issuecomment-463867081

Anyway, the always-on-top is intentional and hardcoded for the external-UI meter plugins.
You could re-compile the plugins with `make CPPFLAGS="-DDEFAULT_NOT_ONTOP"` ...

I can also imagine allowing to override this using a environment variable. That would at least allow power-users to disable this as needed.

**Comment by BlueMax** [comment]
> I can also imagine allowing to override this using a environment variable. That would at least allow power-users to disable this as needed.

That would be great. :+1: 

> I never found a spectrum-analyzer by itself useful in musical context

Not sure if we talk about the same thing. A [spectrogram](https://en.wikipedia.org/wiki/Spectrogram) is a spectrum-analyzer over time. You can see the notes and voices. The 'wolf spectrum' plugin is somewhat limited though and has precision problems/bugs. No round-robin updates, always scrolls the whole graphic buffer (motion sickness, high cpu), no horizontal view and no on-screen knobs/options at all yet. Its probably in a very early stage i guess.

![wolf](https://user-images.githubusercontent.com/1403092/61252602-579a3880-a75e-11e9-9952-a82c7cccf5c7.png)

**Comment by x42** [comment]
x42-eq features a waterfall display, although it doesn't look as "fancy" :)

Anyway in current git you can set `X42_ON_TOP=0` and the plugin won't be always on top anymore. 
Also recent Carla development version will inform the plugin to remain on-to-of the Carla itself.

**Comment by BlueMax** [comment]
This is very good news. Thank you very much.
